#:schema node_modules/wrangler/config-schema.json
name = "comwit-api"
main = "src/index.ts"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "comwit"
database_id = "fbba6c62-2ac7-4f60-a81d-422c2247ddc7"
migrations_dir = "./migrations"
