#:schema node_modules/wrangler/config-schema.json
name = "cozy-blog"
main = "src/index.ts"
workers_dev = true
compatibility_date = "2024-07-12"
compatibility_flags = ["nodejs_compat"]
account_id = "a0f0622b36d5e55324b4a3ee91ab6708"

[[d1_databases]]
binding = "DB"
database_name = "cozy-blog"
database_id = "4a9b81b1-12da-4e9b-96fb-760d567595db"
