#:schema node_modules/wrangler/config-schema.json
name = "comwit-api"
main = "src/index.ts"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "comwit"
database_id = "ba22eb0a-b916-44bd-8cab-5459f151a962"
migrations_dir = "./migrations"
